Error code,Parameters,Description
source-validator.UrlMustBeString,url_type,"Key ‘url’ in your request must be a string, got {url_type} instead."
source-validator.UrlMustBeLink,,Your URL must be a link starting with “http://” or “https://”.
source-validator.UrlFormatInvalid,parse_error_message,Format of ‘url’ is invalid and cannot be parsed. Error: {parse_error_message}
source-validator.ZoomMustBeInteger,actual_zoom,"Zoom must be either empty, or integer, got {actual_zoom}"
source-validator.InvalidZoomValue,actual_zoom},"Zoom must be between 0 and 22, got {actual_zoom}"
source-validator.TooHighZoom,"max_zoom, actual_zoom","Zoom must be not higher than {max_zoom}, got {actual_zoom}"
source-validator.TooLowZoom,"min_zoom, actual_zoom","Zoom must be not lower than {min_zoom}, got {actual_zoom}"
source-validator.UrlBlacklisted,url,"The specified basemap {url} is forbidden for processing because it contains a map, not satellite image. Our models are suited for satellite imagery."
source-validator.ImageMetadataMustBeDict,,Image metadata must be a dict (json)
source-validator.ImageMetadataKeyError,,"Image metadata must have keys: crs, transform, dtype, count"
source-validator.S3URLError,actual_s3_link,"URL of the image at s3 storage must be a string starting with s3://, got {actual_s3_link}"
source-validator.LocalRequestKeyError,,Request must contain either ‘profile’ or ‘url’ keys
source-validator.ReadFromS3Failed,s3_link,Failed to read file from {s3_link}.
source-validator.ImageReadError,,We could not open and read the image you have uploaded
source-validator.BadImageProfile,"profile, required_keys","Image profile (metadata) must have keys {required_keys}, got profile {profile}"
source-validator.DtypeNotAllowed,"required_dtypes, request_dtype","Image data type (Dtype) must be one of {required_dtypes}, got {request_dtype}"
source-validator.NChannelsNotAllowed,"required_nchannels, real_nchannels",Number of channels in image must be one of {required_nchannels}. Got {real_nchannels}
source-validator.PixelSizeTooLow,"actual_res, min_res","Spatial resolution of you image is too low: pixel size is {actual_res}, minimum allowed pixel size is {min_res}"
source-validator.PixelSizeTooHigh,"actual_res, max_res","Spatial resolution of you image is too high: pixel size is {actual_res}, maximum allowed pixel size is {max_res}"
source-validator.ImageCheckError,"checked_param, message, metadata",Error occurred during image {checked_param} check: {message}. Image metadata = {metadata}.
source-validator.QuadkeyLinkFormatError,,"Your ‘url’ doesn’t match the format, Quadkey basemap must be a link containing “q” placeholder."
source-validator.SentinelInputStringKeyError,,Sentinel_L2A request must contain field named ‘url’ with string value
source-validator.SentinelInputStringFormatError,input_string,Input string {input_string} is of unknown format. It must represent Sentinel-2 granule ID
source-validator.GridCellOutOfBound,"actual_cell, allowed_cells","Selected Sentinel-2 image cell is {actual_cell}, this model is for the cells: {allowed_cells}"
source-validator.AOINotInCell,actual_cell,AOI does not intersect the selected Sentinel-2 granule {actual_cell}
source-validator.MonthOutOfBounds,"actual_month, allowed_months","Selected Sentinel-2 image month is {actual_month}, this model is for: {allowed_months}"
source-validator.TMSLinkFormatError,,"You request TMS basemap link doesn’t match the format, it must be a link containing ‘{x}’, ‘{y}’, ‘{z}’ placeholders, correct it and start processing again."
source-validator.RequirementsMustBeDict,requirements_type,"Requirements must be dict, got {requirements_type}."
source-validator.RequestMustBeDict,request_type,"Request must be dict, got {request_type}."
source-validator.RequestMustHaveSourceType,,"Request must contain ""source_type"" key"
source-validator.SourceTypeIsNotAllowed,"source_type, allowed_sources",Source type {source_type} is not allowed. Use one of: {allowed_sources}
source-validator.RequiredSectionMustBeDict,required_section_type,"“Required” section of the requirements must contain dict, not {required_section_type}"
source-validator.RecommendedSectionMustBeDict,recommended_section_type,"“Recommended” section of the requirements must contain dict, not {recommended_section_type}"
source-validator.XYZLinkFormatError,,"You XYZ basemap link doesn’t match the format, it must be a link containing ‘{x}’, ‘{y}’, ‘{z}’ placeholders."
source-validator.TaskMustContainAoi,,Task for source-validation must contain area of interest (‘geometry’ section)
source-validator.UnhandledException,,"Internal error in process of data source validation. We are working on the fix, our support will contact you."
source-validator.internalError,,"Internal error in process of data source validation. We are working on the fix, our support will contact you."
dataloader.internalError,,"Internal error in process of loading data. We are working on the fix, our support will contact you."
dataloader.InternalError,,"Internal error in process of loading data. We are working on the fix, our support will contact you."
dataloader.UnknownSourceType,"allowed_source_types, real_source_types",Wrong source type {real_source_type}. Specify one of the allowed types {allowed_source_types}.
dataloader.MemoryLimitExceeded,"allowed_size, estimated_size","Your data loading task requires {estimated_size} MB of memory, which exceeded allowed memory limit {allowed_size}"
dataloader.LoaderArgsError,"argument_name, argument_type, expected_type","Dataloader argument {argument_name} has type {argument_type}, excpected to be {expected_type}"
dataloader.WrongChannelsNum,"expected_nchannels, real_nchannels","Loaded tile has {real_nchannels} channels, required number is {expected_nchannels}"
dataloader.WrongTileSize,"expected_size, real_size","Loaded tile has size {real_size}, expected tile size is {expected_size}"
dataloader.TileNotLoaded,"tile_location, status","Tile at location {tile_location} cannot be loaded, server response is {status}"
dataloader.CrsIsNotSupported,,"Internal error in process of loading data. We are working on the fix, our support will contact you."
dataloader.MaploaderInternalError,,"Internal error in process of loading data. We are working on the fix, our support will contact you."
dataloader.SentinelLoaderInternalError,,"Internal error in process of loading data. We are working on the fix, our support will contact you."
raster-processor.internalError,,"Internal error in process of data preparation. We are working on the fix, our support will contact you."
inference.internalError,,"Internal error in process of data processing. We are working on the fix, our support will contact you"
vector-processor.internalError,,"Internal error in process of data processing. We are working on the fix, our support will contact you"